---
version: '3'
services:
  jdbc-connect:
    image: confluentinc/cp-kafka-connect:5.0.0
    ports:
      - 8084:8084
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_REST_PORT: 8084
      CONNECT_GROUP_ID: jdbc-source-connect
      CONNECT_CONFIG_STORAGE_TOPIC: jdbc-source-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: jdbc-source-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: jdbc-source-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES:
        'no.sysco.middleware.kafka.interceptor.zipkin.TracingProducerInterceptor,
        no.sysco.middleware.kafka.interceptor.config.ConfigHarvesterInterceptor'
      CONNECT_PRODUCER_ZIPKIN_LOCAL_SERVICE_NAME: "jdbc-connect"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES:
        'no.sysco.middleware.kafka.interceptor.zipkin.TracingConsumerInterceptor,
        no.sysco.middleware.kafka.interceptor.config.ConfigHarvesterInterceptor'
    volumes:
      - ./zipkin/target/kafka-interceptor-zipkin-0.1.1-SNAPSHOT.jar:/etc/kafka-connect/jars/kafka-interceptor-zipkin.jar
      - ./config/target/kafka-interceptor-config-0.1.1-SNAPSHOT.jar:/etc/kafka-connect/jars/kafka-interceptor-config.jar
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    ports:
    - 18080:8080